### ISSUE TITLE
I cant place spawners!

### ISSUE THREAD

**Issue by GamerProdigee** [ty2u/spawner#7]
I cant seem to place any spawners?

**Comment by ty2u** [comment]
Do you have permissions set properly? Do you get any errors in the logs?
What versions of everything are you using? What permissions plugin?

**Comment by GamerProdigee** [comment]
Yes I have the all permissions, no I dont only that I cant place it, 1.9.2,
bPermissions.

**Comment by ty2u** [comment]
Sorry for the delay. Got really busy with work.

I didn't know bPermissions was even updated anymore but that's alright if it is. I will test with it and see what I can find out. I'm going to work on getting this plugin updated to 1.10 as well and see if I can fix any issues people have reported.

**Comment by ty2u** [comment]
I tested this and it seemed to work ok for me. I could place and break them fine when in either the default or admin group with the groups.yml in bpermissions set like below.

All I can think is maybe you were adding permissions to the wrong groups.yml file? There is a global groups.yml file which has a config setting in order to use. There are also per world groups.yml files which it seems to use by default and this is where I've put the permissions as shown below.

Either that or maybe some other conflicting plugin somewhere or a previous bug which has since been fixed. I am testing on a dev build of the Spawner plugin which does have some rewritten code but mostly for how it saves the spawner types. I'm also working with the most recent build of spigot so if it was a bug in the past it shouldn't be in the future.

```
default: default
groups:
  default:
    permissions:
    - spawner.get
    - spawner.break.all
    - spawner.place.all
    - spawner.help
    - spawner.list
    groups: []
  admin:
    permissions:
    - spawner.all
    groups: []
```
